compressionLevel: mixed

enableGlobalCache: false

packageExtensions:
  "@babel/plugin-syntax-flow@*":
    dependencies:
      "@babel/core": "*"
  "@babel/plugin-transform-react-jsx@*":
    dependencies:
      "@babel/core": "*"
  "@testing-library/user-event@*":
    dependencies:
      "@testing-library/dom": "*"
  eslint-plugin-flowtype@*:
    dependencies:
      "@babel/plugin-syntax-flow": "*"
      "@babel/plugin-transform-react-jsx": "*"

yarnPath: .yarn/releases/yarn-4.2.2.cjs
