packageExtensions:
  eslint-plugin-flowtype@*:
    dependencies:
      "@babel/plugin-syntax-flow": "*"
      "@babel/plugin-transform-react-jsx": "*"
  "@babel/plugin-syntax-flow@*":
    dependencies:
      "@babel/core": "*"
  "@babel/plugin-transform-react-jsx@*":
    dependencies:
      "@babel/core": "*"
  "@testing-library/user-event@*":
    dependencies:
      "@testing-library/dom": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.2.2.cjs
